# Generated by Django 4.1.7 on 2023-06-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainanceRequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('completed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.student')),
            ],
        ),
    ]
