# Generated by Django 4.1.7 on 2023-06-03 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0002_maintainancerequestdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='RESTAPI.student')),
            ],
        ),
    ]
